spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///java_blog_server?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=UTC
    username: root
    password: 0438424142c
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

mybatis:
  type-aliases-package: com.cg.blog.pojo
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  map-underscore-to-camel-case: true


logging:
    level:
      com.cg.blog: debug